### ISSUE TITLE
Vypracovaný úkol - statistika

### ISSUE THREAD

**Issue by PetraJurcagova** [PetraJurcagova/Statistika#1]
@vaclavcepelak Ahoj, prosím podívej se na řešení. Snad jsem si zadání přeložila správně. Díky Petra

**Comment by vaclavcepelak** [comment]
Ahoj Petro, poradila sis s tím skvěle! Nenašel jsem tam žádnou chybu a přeložila sis to správně. V rámci toho, co jsme se na kurzu učili, nemám co vytknout a úkol je splněn. Pokud by sis chtěla udělat bonus 3, bylo by to super, protože kategorické proměnné v regresi určitě využiješ.

Teď poznámky na okraj, které ber spíš jako "radu do života"
- Základní rada je si udělat co nejvíc grafů: distribuce hodnot (`sns.histplot(data["Y"], kde=True)`), distribuce reziduí (`sns.histplot(result.resid, kde=True)`), regresní graf predikovaných a skutečných hodnot (`sns.regplot(data, x="Predicted_Y", y="Y")`) - ten ti ukáže, že tam je pár odlehlých pozorování, která jsou extrémně vlivná. Z těch grafů většinou dokážeš odhalit, že v datech je něco nečekaného - nějaký problém, který je třeba řešit.
- To je taky důvod, proč ti vyšlo R2 ve druhém případě tak nízké. Ten model prostě těch pár případů netrefil, protože k tomu potřeboval hodnoty z těch sloupců, které jsi vyřadila. Obecně tady máme málo dat s "nenormální" distribucí, takže ten model je pak hodně nestabilní a s jakoukoliv změnou všechno strašně lítá. (Myslím, že je to trochu nešťastně vybraný úkol, ale zas aspoň vidíš, že v životě nepracuješ jen s hezkými daty.)
- Ten problém se ukazuje i v nenormalitě reziduí (Jarque-Beta test - bylo to v lekci 6)

Formální doporučení:
- Dát do toho notebooku i zadání úkolu. Třeba se k tomu budeš chtít jednou vrátit nebo to ukázat někomu během pohovoru ;-). 
- Nedohlédávat nic v datech podle indexu. Může se stát, že si index cestou někde změníš a budeš to mít špatně. Pracuj raději pořád s jedním data framem, kde si necháš všechny informace. Ten si můžeš seřadit celý (`data.sort_values(by="<nazev_sloupce>", ascending=False)`)
- Na druhou stranu, když data měníš (odmazáváš z nich řádky), založ si raději nová data (pokud paměť dovolí) a pracuj dál s nimi. Může se stát, že budeš ta původní potřebovat a budeš pak muset spouštět celý skript znova.
- Fakt všechny importy dej na začátek notebooku (když ti ten notebook začne bobtnat, budeš v tom mít guláš).

Pokud se budeš chtít podívat na úlohu 3, dej vědět. Jinak to zavřeme.

Díky, V.

**Comment by PetraJurcagova** [comment]
Ahoj Vašku,
díky moc za zpětnou vazbu a kontrolu. Jsem ráda, že se
zadařilo. 🥳 Doporučení si beru k srdci a mrknu na to ať to mám na pohovoru
pěkné 😁. Veškerá statistika v kurzu je pro mě novinkou a nemám témata
ještě zažitá.
Nevěděla jsem, jak na třetí bonus. Nepodařilo se mi v materiálech dohledat,
co přesně je One hot encoding a jak s tím naložit. Možná, že jsem to jen
přehlédla a je to v nepovinných kapitolách. Každopádně, kdyby jsi měl
nějaký typ, jak postupovat nebo, kde hledat, budu ráda.

Díky Petra

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Neobsahuje
žádné viry.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

ne 5. 11. 2023 v 22:03 odesílatel Václav Čepelák ***@***.***>
napsal:
